// Next
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Styles
import './globals.css';

// Components
import Header from '@/components/globals/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={inter.className}
				suppressHydrationWarning
				style={{ height: 5000 }}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
